# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=5)),
                ('section', models.CharField(default='', max_length=1)),
                ('year', models.IntegerField(default=1)),
                ('no_of_students', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendenceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(default='', max_length=10)),
                ('subject_name', models.CharField(default='', max_length=32)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAttendenceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_count', models.IntegerField(default=0)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='StudentManagementSystem.DailyTimeTable')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='StudentManagementSystem.DailyTimeTable')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='StudentManagementSystem.DailyTimeTable')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='StudentManagementSystem.DailyTimeTable')),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='StudentManagementSystem.DailyTimeTable')),
            ],
        ),
        migrations.AddField(
            model_name='studentattendencetable',
            name='subject1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='StudentManagementSystem.SubjectAttendenceTable'),
        ),
        migrations.AddField(
            model_name='studentattendencetable',
            name='subject2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='StudentManagementSystem.SubjectAttendenceTable'),
        ),
        migrations.AddField(
            model_name='studentattendencetable',
            name='subject3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='StudentManagementSystem.SubjectAttendenceTable'),
        ),
        migrations.AddField(
            model_name='studentattendencetable',
            name='subject4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='StudentManagementSystem.SubjectAttendenceTable'),
        ),
        migrations.AddField(
            model_name='studentattendencetable',
            name='subject5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject5', to='StudentManagementSystem.SubjectAttendenceTable'),
        ),
        migrations.AddField(
            model_name='studentattendencetable',
            name='subject6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject6', to='StudentManagementSystem.SubjectAttendenceTable'),
        ),
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.StudentAttendenceTable'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.Class'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period1', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period2', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period3', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period4', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period5', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period6', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='period7',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period7', to='StudentManagementSystem.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='time_table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.WeeklyTimeTable'),
        ),
    ]
