# Generated by Django 5.0.1 on 2024-02-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0002_rename_studentattendencetable_studentattendancetable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytimetable',
            name='period6',
        ),
        migrations.RemoveField(
            model_name='dailytimetable',
            name='period7',
        ),
        migrations.RemoveField(
            model_name='studentattendancetable',
            name='subject6',
        ),
    ]
