# Generated by Django 5.0.1 on 2024-02-29 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0003_remove_dailytimetable_period6_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklytimetable',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='weeklytimetable',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='weeklytimetable',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='weeklytimetable',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='weeklytimetable',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='studentattendancetable',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='studentattendancetable',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='studentattendancetable',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='studentattendancetable',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='studentattendancetable',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='subjectattendancetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='class',
            name='time_table',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ManyToManyField(to='StudentManagementSystem.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyTimeTable',
        ),
        migrations.DeleteModel(
            name='StudentAttendanceTable',
        ),
        migrations.DeleteModel(
            name='SubjectAttendanceTable',
        ),
        migrations.DeleteModel(
            name='WeeklyTimeTable',
        ),
    ]
