# Generated by Django 5.0.1 on 2024-02-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0004_remove_weeklytimetable_tuesday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='faculty',
            new_name='faculties',
        ),
    ]
