# Generated by Django 5.0.1 on 2024-02-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0005_rename_faculty_teacher_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.CharField(default='', max_length=10),
        ),
    ]
