# Generated by Django 5.0.1 on 2024-02-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0006_alter_class_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.subject'),
        ),
    ]
