# Generated by Django 5.0.1 on 2024-02-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0007_class_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(to='StudentManagementSystem.subject'),
        ),
    ]
