# Generated by Django 5.0.1 on 2024-02-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0008_remove_class_subject_class_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.teacher'),
            preserve_default=False,
        ),
    ]
