# Generated by Django 5.0.1 on 2024-02-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0010_alter_class_branch_alter_class_no_of_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=10),
        ),
    ]
