# Generated by Django 5.0.1 on 2024-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0014_remove_subject_faculty_remove_teacher_faculties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='StudentManagementSystem.subject'),
        ),
    ]
